# Generated by Django 3.2.8 on 2021-10-18 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MrbBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notion_synced', models.BooleanField(db_index=True, default=False)),
                ('notion_id', models.TextField(blank=True, db_index=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MrbChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notion_synced', models.BooleanField(db_index=True, default=False)),
                ('notion_id', models.TextField(blank=True, db_index=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MrbMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notion_synced', models.BooleanField(db_index=True, default=False)),
                ('notion_id', models.TextField(blank=True, db_index=True, null=True)),
                ('unique_msg_id', models.CharField(max_length=63, unique=True)),
                ('plain_text', models.TextField(blank=True, null=True)),
                ('text_entities', models.JSONField(blank=True, null=True)),
                ('from_user', models.BooleanField()),
                ('sent_timestamp', models.BigIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MrbUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notion_synced', models.BooleanField(db_index=True, default=False)),
                ('notion_id', models.TextField(blank=True, db_index=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MrbBotMessage',
            fields=[
                ('mrbmessage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='moonrobot.mrbmessage')),
                ('url_suffix', models.TextField(blank=True, null=True)),
                ('request_payload', models.JSONField(blank=True, null=True)),
                ('response_payload', models.JSONField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('moonrobot.mrbmessage',),
        ),
        migrations.CreateModel(
            name='MrbUserMessage',
            fields=[
                ('mrbmessage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='moonrobot.mrbmessage')),
                ('update_payload', models.JSONField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('moonrobot.mrbmessage',),
        ),
    ]
