# Generated by Django 3.2.8 on 2021-10-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moonrobot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mrbbotmessage',
            name='request_method',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mrbbotmessage',
            name='request_payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mrbbotmessage',
            name='response_payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mrbusermessage',
            name='update_payload',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
