# Generated by Django 3.2.8 on 2021-10-10 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moonrobot', '0002_auto_20211010_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mrbbotmessage',
            old_name='request_method',
            new_name='url_suffix',
        ),
    ]
