# Generated by Django 3.2.8 on 2021-10-28 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moonrobot', '0002_mrbmessage_user_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mrbmessage',
            name='user_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mrbmessage',
            name='username',
            field=models.TextField(blank=True, null=True),
        ),
    ]
