# Generated by Django 3.2.8 on 2021-10-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moonrobot', '0003_auto_20211028_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='mrbmessage',
            name='chat_id',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='mrbmessage',
            index=models.Index(fields=['chat_id', 'sent_timestamp'], name='moonrobot_m_chat_id_7da470_idx'),
        ),
    ]
