# Generated by Django 3.2.8 on 2021-10-10 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moonrobot', '0003_rename_request_method_mrbbotmessage_url_suffix'),
    ]

    operations = [
        migrations.AddField(
            model_name='mrbmessage',
            name='plain_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
