# Generated by Django 3.2.8 on 2021-10-11 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moonrobot', '0004_mrbmessage_plain_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='mrbchat',
            name='notion_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mrbchat',
            name='notion_synched',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='mrbmessage',
            name='notion_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mrbmessage',
            name='notion_synched',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='mrbuser',
            name='notion_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mrbuser',
            name='notion_synched',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
