# Generated by Django 3.2.8 on 2021-10-31 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moonrobot', '0005_mrbmessage_moonrobot_m_notion__b5567c_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='mrbmessage',
            name='moonrobot_m_notion__b5567c_idx',
        ),
        migrations.AddField(
            model_name='mrbbot',
            name='notion_sync_failed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mrbchat',
            name='notion_sync_failed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mrbmessage',
            name='notion_sync_failed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mrbuser',
            name='notion_sync_failed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mrbbot',
            name='notion_synced',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mrbchat',
            name='notion_synced',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mrbmessage',
            name='notion_synced',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mrbuser',
            name='notion_synced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='mrbmessage',
            index=models.Index(fields=['notion_synced', 'notion_sync_failed', 'sent_timestamp'], name='moonrobot_m_notion__82cecb_idx'),
        ),
    ]
