# Generated by Django 3.2.8 on 2021-10-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moonrobot', '0005_auto_20211011_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='mrbmessage',
            name='from_user',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
