# Generated by Django 3.2.8 on 2021-10-16 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moonrobot', '0009_mrbbot'),
    ]

    operations = [
        migrations.AddField(
            model_name='mrbmessage',
            name='sent_timestamp',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
