# Generated by Django 3.2.8 on 2021-10-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moonrobot', '0010_mrbmessage_sent_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mrbbot',
            name='notion_id',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='mrbchat',
            name='notion_id',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='mrbmessage',
            name='notion_id',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='mrbuser',
            name='notion_id',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
    ]
