# Generated by Django 3.2.8 on 2021-10-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moonrobot', '0011_auto_20211017_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='mrbmessage',
            name='unique_msg_id',
            field=models.CharField(db_index=True, default='', max_length=63),
            preserve_default=False,
        ),
    ]
